import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Calora",
  description:
    "Terms of using Calora. TL;DR: Calora is not a medical device. Calorie and macro estimates are approximations and may be inaccurate by 15-30%.",
};

export default function TermsPage() {
  return (
    <main className="min-h-[100dvh] bg-[var(--canvas)]">
      <div className="max-w-2xl mx-auto px-5 py-12">
        <Link
          href="/"
          className="text-[13px] text-[var(--ink-soft)] hover:text-[var(--ink)] transition inline-flex items-center gap-1 mb-8"
        >
          ← Back to calora
        </Link>

        <h1 className="font-[family-name:var(--font-display)] text-[36px] font-semibold tracking-[-0.02em] text-[var(--ink)] mb-2">
          Terms of Service
        </h1>
        <p className="text-[13px] text-[var(--ink-muted)] mb-8">
          Effective 2026-07-12
        </p>

        <div className="p-4 rounded-[14px] bg-[var(--warning-soft)] border border-[var(--warning)]/20 mb-10">
          <p className="text-[15px] text-[var(--ink)] font-semibold mb-1">
            ⚠️ Not a medical device
          </p>
          <p className="text-[13.5px] text-[var(--ink-soft)] leading-relaxed">
            Calora is an informational tool, not a medical device. Calorie and
            macro estimates are generated by AI and may be inaccurate by
            15-30%. Do not use Calora to diagnose, treat, cure, or prevent any
            medical condition. Consult a qualified healthcare professional for
            medical nutrition advice.
          </p>
        </div>

        <div className="space-y-8 text-[15px] text-[var(--ink)]">
          <section>
            <h2 className="font-[family-name:var(--font-display)] text-[20px] font-semibold tracking-[-0.01em] mb-3">
              1. Acceptance
            </h2>
            <p className="text-[var(--ink-soft)] leading-relaxed">
              By using Calora, you agree to these terms. If you don&apos;t
              agree, don&apos;t use Calora.
            </p>
          </section>

          <section>
            <h2 className="font-[family-name:var(--font-display)] text-[20px] font-semibold tracking-[-0.01em] mb-3">
              2. The service
            </h2>
            <p className="text-[var(--ink-soft)] leading-relaxed mb-3">
              Calora provides AI-generated estimates of calories and macros
              for food you photograph or describe in text. The service is
              provided &quot;as is&quot; without warranties of any kind.
            </p>
            <p className="text-[var(--ink-soft)] leading-relaxed">
              We may modify, pause, or discontinue the service at any time
              with reasonable notice to paying subscribers.
            </p>
          </section>

          <section>
            <h2 className="font-[family-name:var(--font-display)] text-[20px] font-semibold tracking-[-0.01em] mb-3">
              3. Free tier
            </h2>
            <p className="text-[var(--ink-soft)] leading-relaxed">
              The free tier includes up to 5 meal scans per day (Pacific time
              reset). We may change this limit with 30 days notice. The free
              tier is provided without warranty of availability.
            </p>
          </section>

          <section>
            <h2 className="font-[family-name:var(--font-display)] text-[20px] font-semibold tracking-[-0.01em] mb-3">
              4. Pro subscription
            </h2>
            <p className="text-[var(--ink-soft)] leading-relaxed mb-3">
              Pro costs $4.99/month or $29.99/year. You can cancel anytime from
              Settings → Manage Subscription; you keep Pro access until the
              end of your current billing period.
            </p>
            <p className="text-[var(--ink-soft)] leading-relaxed mb-3">
              <strong>Free trial:</strong> New Pro subscribers get a 7-day free
              trial. We email you 24 hours before the trial ends. If you do
              nothing, you&apos;ll be charged at the end of the trial. Cancel
              anytime during the trial — no charge.
            </p>
            <p className="text-[var(--ink-soft)] leading-relaxed">
              <strong>Refunds:</strong> We offer a 30-day money-back guarantee
              on annual subscriptions. Contact support for a full refund.
              Monthly subscriptions are not refundable but you keep access
              until the end of the period.
            </p>
          </section>

          <section>
            <h2 className="font-[family-name:var(--font-display)] text-[20px] font-semibold tracking-[-0.01em] mb-3">
              5. Your data
            </h2>
            <p className="text-[var(--ink-soft)] leading-relaxed">
              See our <Link href="/privacy" className="text-[var(--accent)] underline">Privacy Policy</Link>.
              Summary: you own your data, you can export it, you can delete
              it.
            </p>
          </section>

          <section>
            <h2 className="font-[family-name:var(--font-display)] text-[20px] font-semibold tracking-[-0.01em] mb-3">
              6. Acceptable use
            </h2>
            <p className="text-[var(--ink-soft)] leading-relaxed mb-3">
              You agree not to:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-[var(--ink-soft)]">
              <li>Use Calora to harass, harm, or track other people</li>
              <li>Reverse engineer or attempt to extract source code</li>
              <li>
                Abuse the free tier with automated scripts (we rate-limit at
                10 requests/minute per IP)
              </li>
              <li>
                Upload images that contain child sexual abuse material,
                non-consensual intimate imagery, or other illegal content
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-[family-name:var(--font-display)] text-[20px] font-semibold tracking-[-0.01em] mb-3">
              7. Limitation of liability
            </h2>
            <p className="text-[var(--ink-soft)] leading-relaxed">
              Calora is not liable for any damages arising from your use of the
              service, including but not limited to dietary decisions,
              weight-loss outcomes, allergic reactions, or interactions with
              medical conditions. Use at your own risk.
            </p>
          </section>

          <section>
            <h2 className="font-[family-name:var(--font-display)] text-[20px] font-semibold tracking-[-0.01em] mb-3">
              8. Changes to these terms
            </h2>
            <p className="text-[var(--ink-soft)] leading-relaxed">
              Material changes will be communicated to Pro subscribers at least
              14 days before they take effect. Continued use after the
              effective date constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="font-[family-name:var(--font-display)] text-[20px] font-semibold tracking-[-0.01em] mb-3">
              9. Contact
            </h2>
            <p className="text-[var(--ink-soft)] leading-relaxed">
              Questions? Email{" "}
              <a
                href="mailto:hello@calora.app"
                className="text-[var(--accent)] underline"
              >
                hello@calora.app
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}